import { Text,Image, StyleSheet } from 'react-native';
import SearchBar from "../components/SearchBar";
import Header, { HeaderBack, HeaderCenterContainer, HeaderLeftLogo, HeaderLeftRightBtton, SearchBarContainer } from '../components/Header';
import { Background, Scroll } from '../components/Screens';


const Home = () =>{
    return (
        <Background>
            <Scroll>
                <HeaderBack/>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>home</Text>
                <Text>last</Text>
            </Scroll>
            <Header>
                <HeaderLeftLogo src={require("../assets/homeLogo.png")}></HeaderLeftLogo>
                <SearchBarContainer><SearchBar/></SearchBarContainer>
            </Header>
        </Background>
    )
}

export default Home;

const styles = StyleSheet.create({
    logo: {
        width: 103,
        height: 68,
    }
})
