import { Text } from 'react-native';
import Header from '../components/Header';
import { Background, Scroll } from '../components/Screens';

const List = () =>{
    return (
        <Background>
            <Scroll>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>last</Text>
            </Scroll>
            <Header/>
        </Background>
    )
}

export default List;