import { Text } from 'react-native';
import Header, { HeaderBack, HeaderLeftLogo, SearchBarContainer } from '../components/Header';
import { Background, Scroll } from '../components/Screens';
import SearchBar from "../components/SearchBar";

const List = () =>{
    return (
        <Background>
            <Scroll>
                <HeaderBack></HeaderBack>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>list</Text>
                <Text>last</Text>
            </Scroll>
            <Header>
                <HeaderLeftLogo src={require("../assets/homeLogo.png")}></HeaderLeftLogo>
                <SearchBarContainer><SearchBar/></SearchBarContainer>
            </Header>
        </Background>
    )
}

export default List;