import { Text } from 'react-native';
import Header from '../components/Header';
import { Background, Scroll } from '../components/Screens';

const MapScreen = () =>{
    return (
        <Background>
            <Scroll>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>map</Text>
                <Text>last</Text>
            </Scroll>
            <Header/>
        </Background>
    )
}

export default MapScreen;