import { Text, Image, StyleSheet } from 'react-native';
import Header from '../components/Header';
import { Background, Scroll } from '../components/Screens';

const Personal = () =>{
    return (
        <Background>
            <Scroll>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>personal</Text>
                <Text>last</Text>
            </Scroll>
            <Header>
                
            </Header>
        </Background>
    )
}

export default Personal;

